name: doctor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0
  country_code_picker: 2.0.2
  percent_indicator: ^3.0.1
  
  url_launcher: ^6.0.18
  otp_text_field: ^1.1.3
  firebase_core: ^1.21.1
  provider: ^6.0.3
  http: ^0.13.5
  scroll_date_picker: ^3.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.10.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imges/app_logo.png"
  min_sdk_android: 21 

flutter:

  uses-material-design: true

  assets:
    - images/