// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5MUi4wXBYIs5QckAqnbtm2CYRZCoWpw',
    appId: '1:1066105525052:android:f1b62b59a914c0bcb54439',
    messagingSenderId: '1066105525052',
    projectId: 'crackerit-6b0e9',
    storageBucket: 'crackerit-6b0e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpAso4qewuCpT0j_QGO03H7kXRVuQRsck',
    appId: '1:1066105525052:ios:b9ec8fc119bf7339b54439',
    messagingSenderId: '1066105525052',
    projectId: 'crackerit-6b0e9',
    storageBucket: 'crackerit-6b0e9.appspot.com',
    androidClientId: '1066105525052-60dgvlo3q4co01h0v1e46hfb934diq3a.apps.googleusercontent.com',
    iosClientId: '1066105525052-d9o9k5bs85fjhvl97cpn9c7643gm5cqk.apps.googleusercontent.com',
    iosBundleId: 'com.crackit.doctor',
  );
}
